### ISSUE TITLE
[Question]: About connect to specify tenant and cluster

### ISSUE THREAD

**Issue by thehaung** [oceanbase/ob-example#22]
### Description

Hi guy, I try to connect to the oceanbase tenant in Golang with following guide but this can't establish connection. But in the Java with JDBC it's works well

**Comment by whhe** [comment]
The Mysql mode of OceanBase should be compatible with the commen mysql driver and you just need to use the username in specific format `user@tenant#cluster`, if you meet any issues, please provide your environment information like driver name and versions, and the output of your application.

**Comment by thehaung** [comment]
Here is my dependencies and connection information

Go: 1.20
MySQL driver: github.com/go-sql-driver/mysql v1.7.0
UserName: teamA@rift#dazz:4
Password: Telegrapth#676A@A

My function for build datasource
func buildDateSourceUrl(conf config.OceanBase) string {
	return fmt.Sprintf("%s:%s@tcp(%s:%s)/%s",
		url.QueryEscape(conf.UserName), url.QueryEscape(conf.Password), conf.Host, conf.Port, conf.DatabaseName)
}

Error: sql.Open. Error 1045 (42000): Access denied for user 'teamA%40rift%dazz%3A4@sys'@'<ip>' (using password: YES)

**Comment by whhe** [comment]
Looks like the issue is caused by the escape process, what if you pass the original username and password to the datasource url?

**Comment by thehaung** [comment]
No, the same result occur, nothing happens

**Comment by whhe** [comment]
I find that there is a colon in your username and maybe it will break the url format, you can have a try with the plain text `teamA@rift#dazz` which does not contain the cluster id and colon.

**Comment by thehaung** [comment]
I change with the following guide, but this not work

**Comment by whhe** [comment]
What is the error output?

`Access denied for user 'teamA%40rift%dazz%3A4@sys'@'' (using password: YES)`

This error message shows that the database did not receive the username in format `user@tenant#cluster`, so it use the username `teamA%40rift%dazz%3A4` in which no cluster and tenant are specificed, and try to auth it with the default tenant `sys`.

**Comment by thehaung** [comment]
No I tried in the Database tools, JDBC in Java. It's worked

**Comment by thehaung** [comment]
Hi @whhe maybe I make the mistake your solution worked for me. But when I concern what happen when I want connect to specify cluster id

**Comment by whhe** [comment]
As https://github.com/go-sql-driver/mysql/issues/591 is not fixed for now, you can't use colon in username with it. One alternative way is to open connections using the OpenDB method.

```go
config := &mysql.Config{
	Addr:   "",
	User:   "",
	Passwd: "",
	DBName: "",
}
connector, err := mysql.NewConnector(config)
db := sql.OpenDB(connector)
```

**Comment by thehaung** [comment]
Thanks for support @whhe
